=== dimakhodosevich/spring_course_main/target/classes/location.dtd
<!ELEMENT locations (location*)>
<!ELEMENT location (city, population, language)>
<!ATTLIST location id TYPE (#PCDATA) #IMPLIED>
<!ELEMENT city (#PCDATA)>
<!ELEMENT population (#PCDATA)>
<!ELEMENT language (#PCDATA)>

=== dimakhodosevich/spring_course_main/target/classes/location.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE locations SYSTEM "D:\spring_course_main\resources\location.dtd">

<locations>
    <location id="1">
        <city></city>
        <population></population>
        <language></language>
    </location>
    
    <location>
        <city></city>
        <population></population>
        <language></language>
    </location>
    
</locations>
